objective: 'binary'
boosting: "gbdt"
metric: 'auc'
learning_rate: 0.01
num_leaves: 63
max_depth: -1
# min_data_in_leaf: 30 
# min_child_samples: 20
# feature_fraction: 0.9
# bagging_freq: 1
# bagging_fraction: 0.9
# bagging_seed: 11
# lambda_l1: 0.1
verbosity: -1
nthread: -1
random_state: 16
